name: Release Notifications

on:
  release:
    types: [published]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: your-org/slack-release-notifications@v1
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }} 